Docs: translate docs/user-guide/index.md
eslint/cn.eslint.org pull request #44
Opened 2021-08-15 05:37 UTC by Davont

2021-08-15 12:58 UTC, KnowsCount commented on docs/user-guide/index.md
> +想要跳过开头直接开始使用 ESLint 吗？本章节给出了一个关于安装，设置和配置选项的高层次概述。
```suggestion
想跳过前面的步骤直接开始使用 ESLint 吗？本章节给出了一个关于安装，设置和配置选项的高层次概述。
```

感觉这么翻也不是很好，但是 “跳过开头” 似乎太偏了点

2021-08-15 12:58 UTC, KnowsCount commented on docs/user-guide/index.md
> +ESLint 有很多规则，你可以配置这些规则做出相应的调整来配合你的项目。本章节详细的列举了每个规则并且链接到每个规则的文档。
```suggestion
ESLint 有很多规则，你可以配置这些规则以配合你的项目。本章节详细的列举了每个规则并且链接到每个规则的文档。
```

2021-08-15 13:03 UTC, KnowsCount commented on docs/user-guide/index.md
> +ESLint 团队致力于尽可能精简的无痛升级。本节概述了团队为在未来版本中弃用规则而制定的准则。
```suggestion
ESLint 团队致力于使升级尽可能精简并无痛。本章节概述了团队为在未来版本中弃用规则而制定的准则。
```

“本章节” 为了与上文统一。

2021-08-15 13:04 UTC, KnowsCount commented on docs/user-guide/index.md
> +如果你在使用 ESLint 之前的版本，你可以通过阅读以下内容来获得版本过渡的帮助：
```suggestion
如果你在使用早期版本的 ESLint，你可以通过阅读以下内容来获得版本过渡方面的帮助：
```

2021-08-15 13:07 UTC, KnowsCount commented on docs/user-guide/index.md
> +ESLint 有很多命令行标识，本章节将一一解释它们的作用。
@QC-L “命令行标志” 感觉是 command line flags 的一个好翻译……Google 上搜 “命令行标识” 会跳出 “命令行标志” 的结果……但是我的 “参数” 以及你的 “选项” 不会很明显的表示 flag。

2021-08-15 13:08 UTC, KnowsCount commented
总体上翻译的很准确！里头有几个小问题，我都在上头列出了。

2021-08-16 14:18 UTC, Davont commented on docs/user-guide/index.md
> +ESLint 有很多规则，你可以配置这些规则做出相应的调整来配合你的项目。本章节详细的列举了每个规则并且链接到每个规则的文档。
已修改

2021-08-16 14:18 UTC, Davont commented on docs/user-guide/index.md
> +如果你在使用 ESLint 之前的版本，你可以通过阅读以下内容来获得版本过渡的帮助：
已修改

2021-08-16 14:19 UTC, Davont commented on docs/user-guide/index.md
> +ESLint 有很多命令行标识，本章节将一一解释它们的作用。
暂时我改成 “命令行标志” 了哈

2021-08-16 14:19 UTC, Davont commented on docs/user-guide/index.md
> +ESLint 团队致力于尽可能精简的无痛升级。本节概述了团队为在未来版本中弃用规则而制定的准则。
已修改

2021-08-17 03:16 UTC, Ivocin requested changes
添加了2个空格

2021-08-17 03:16 UTC, Ivocin commented on docs/user-guide/index.md
> +# 用户指南{#user-guide}
```suggestion
# 用户指南 {#user-guide}
```

2021-08-17 03:16 UTC, Ivocin commented on docs/user-guide/index.md
> +## [配置ESLint](configuring/) {#configuring}
```suggestion
## [配置 ESLint](configuring/) {#configuring}
```

2021-08-17 04:25 UTC, Davont commented on docs/user-guide/index.md
> +# 用户指南{#user-guide}
已添加

2021-08-17 04:25 UTC, Davont commented on docs/user-guide/index.md
> +## [配置ESLint](configuring/) {#configuring}
已添加

2021-08-18 05:16 UTC, KnowsCount commented
@Davont 你可以直接加入我们 review 更改的

2021-08-18 08:48 UTC, Davont commented
> @Davont 你可以直接加入我们 review 更改的



> @Davont 你可以直接加入我们 review 更改的

抱歉，我在该pr里面，没找到对应操作诶，我这边只能等@Ivocin 操作。右边导航栏“Reviewers” 我没有设置权限

2021-08-18 10:51 UTC, KnowsCount commented
@Davont 我的意思是说，你可以点击 add suggestion to batch 最后 commit suggestion，然后就不用自己手动提交我们的更改建议了。

2021-08-18 15:53 UTC, Davont commented
> @Davont 我的意思是说，你可以点击 add suggestion to batch 最后 commit suggestion，然后就不用自己手动提交我们的更改建议了。

好的，下次我会试试！咋联系这位老哥呢 @Ivocin  我还想合入后翻译下面的内容

2021-08-18 16:26 UTC, Ivocin approved these changes

2021-08-18 16:27 UTC, merged