translated all liquid files except the liquid file of rules
eslint/cn.eslint.org pull request #52
Opened 2021-09-03 07:09 UTC by KimYangOfCat

2021-09-03 07:24 UTC, Ivocin requested changes
感谢，一些格式问题需要调整下

2021-09-03 07:24 UTC, Ivocin commented on _includes/footer.liquid
> +      <li>版权归OpenJS基金会和其他贡献者所有 <a href="https://openjsf.org/">www.openjsf.org</a></li>
```suggestion
      <li>版权归 OpenJS 基金会和其他贡献者所有 <a href="https://openjsf.org/">www.openjsf.org</a></li>
```

2021-09-03 07:24 UTC, Ivocin commented on _includes/footer.liquid
> +        <li><a href="https://github.com/eslint/website/edit/master/{{ page.inputPath }}">编辑此页面</a></li>
此链接是否要改为本仓库链接 @QC-L

2021-09-03 07:24 UTC, Ivocin commented on _includes/text-ad.liquid
> +            <a href="https://opencollective.com/eslint" rel="nofollow" target="_blank"><strong>赞助 ESLint。</strong> ESLint依靠捐赠来进行持续的维护和发展。</a>
```suggestion
            <a href="https://opencollective.com/eslint" rel="nofollow" target="_blank"><strong>赞助 ESLint。</strong> ESLint 依靠捐赠来进行持续的维护和发展。</a>
```

2021-09-03 07:24 UTC, Ivocin commented on _layouts/post.liquid
> +              <p class="text-center">ESLint依赖于个人和公司的支持。<a class="btn btn-default" href="https://opencollective.com/eslint">成为赞助商。</a></p>
```suggestion
              <p class="text-center">ESLint 依赖于个人和公司的支持。<a class="btn btn-default" href="https://opencollective.com/eslint">成为赞助商</a></p>
```

2021-09-03 07:24 UTC, Ivocin commented on _pages/404.liquid
> +   开始使用ESLint »
```suggestion
   开始使用 ESLint »
```

2021-09-03 07:24 UTC, Ivocin commented on _pages/index.liquid
> +    <p class="sponsor-btn text-center"><a class="btn btn-default" href="https://opencollective.com/eslint">现在就成为赞助商吧!</a></p>
```suggestion
    <p class="sponsor-btn text-center"><a class="btn btn-default" href="https://opencollective.com/eslint">现在就成为赞助商吧！</a></p>
```

2021-09-03 07:24 UTC, Ivocin commented on yarn.lock
> +codemirror@^5.58.2:
yarn.lock 文件需要更新吗

2021-09-03 07:27 UTC, KimYangOfCat commented on yarn.lock
> +codemirror@^5.58.2:
如果不需要的话，官方应该会把它添加进 .gitignore 里面吧

2021-09-03 07:29 UTC, KimYangOfCat commented on _includes/footer.liquid
> +      <li>版权归OpenJS基金会和其他贡献者所有 <a href="https://openjsf.org/">www.openjsf.org</a></li>
@lvocin 应该是需要的，我改一下。

2021-09-03 07:30 UTC, KimYangOfCat commented on _includes/footer.liquid
> +        <li><a href="https://github.com/eslint/website/edit/master/{{ page.inputPath }}">编辑此页面</a></li>
@lvocin 应该是需要的，我改一下

2021-09-04 01:42 UTC, KnowsCount commented on _pages/team.liquid
> +<p>他们负责管理发布，审查功能请求，并定期开会以确保 ESLint 得到适当维护。</p>
```suggestion
<p>他们负责管理发行版、审查功能请求、并定期开会以确保 ESLint 得到适当维护。</p>
```

2021-09-06 02:16 UTC, Ivocin commented on yarn.lock
> +codemirror@^5.58.2:
> 如果不需要的话，官方应该会把它添加进 .gitignore 里面吧

好，我看了一下，yarn.lock 是 QC-L 提交的，那更新就没问题

2021-09-06 02:18 UTC, Ivocin approved these changes

2021-09-06 07:19 UTC, Ivocin commented
@KimYangOfCat  还需要签一下这个 License
![image](https://user-images.githubusercontent.com/16836801/132176162-37ed525c-a84e-4df6-9167-9f310d7b2649.png)

2021-09-06 15:23 UTC, KimYangOfCat commented
> @KimYangOfCat 还需要签一下这个 License
> ![image](https://user-images.githubusercontent.com/16836801/132176162-37ed525c-a84e-4df6-9167-9f310d7b2649.png)

finished

2021-09-07 10:00 UTC, merged